# Generated by Django 2.2 on 2025-01-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.site'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='jobs',
            name='task',
            field=models.CharField(blank=True, choices=[('task1', 'task1'), ('task2', 'Task 02'), ('task3', 'Task 03'), ('task4', 'Task 04'), ('task5', 'Task 05')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.userrecords'),
        ),
    ]
