# Generated by Django 2.2 on 2025-01-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_jobs_execution_time_jobs_site_jobs_status_jobs_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.site'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.userrecords'),
        ),
    ]
