# Generated by Django 2.2 on 2025-01-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_jobs_id_alter_site_id_alter_userrecords_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='totaljobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='totalusers',
            field=models.IntegerField(default=0),
        ),
    ]
